openapi: 3.0.0
info:
  description: API, which should be implemented to send messages from CRA IOT portal (https://www.cra.cz/objevte-svet-iot).
  version: "1.0.0"
  title: CRA API
  contact:
    email: tomas@michalicka.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /store:
    post:
      summary: Method to store message
      operationId: storeMessage
      description: Method store given message
      responses:
        '201':
          description: Message stored
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataWrapper'
        description: Inventory item to add
components:
  schemas:
    DataWrapper:
      type: object
      required:
        - type
        - data
      properties:
        type:
          type: string
          example: D
        data:
          $ref: '#/components/schemas/DataItem'
    DataItem:
      type: object
      required:
        - name
      properties:
        cmd:
          type: string
          example: gw
        seqno:
          type: number
          format: int64
          example: 299492020
          description: "Sequence number generated by network server CRA"
        EUI:
          type: string
          example: "10A67EADC8ACF39D"
          description: "Unique device identifier (DevEUI)"
        ts:
          type: number
          format: int64
          example: 1604821874768
          description: "Timestamp"
        fcnt:
          type: number
          format: int64
          example: 0
          description: "Sequence number of message sent from device"
        port:
          type: number
          format: int32
          example: 2
          description: "Device port"
        freq:
          type: number
          format: int64
          example: 867700000
          description: "Frequency [Hz]"
        toa:
          type: number
          format: int32
          example: 31
          description: "Time on air [ms]"
        dr:
          type: string
          example: "SF7 BW125 4/5"
          description: "LoraWAN parameters"
        ack:
          type: boolean
        gws:
          type: array
          description: "List of gateways, which received message."
          items:
            $ref: '#/components/schemas/Gateway'
        bat:
          type: number
          format: int32
          maximum: 255
          minimum: 0
          description: "Battery status (0 - external, 255 - N/A, 1-254 - battery status)"
        data:
          type: string
          description: "Message payload"
        tech:
          type: string
          example: "L"
          description: "Technology used for transport -> L for Lora"
        tags:
          type: array
          items: 
            type: string
    Gateway:
      type: object
      properties:
        rssi:
          type: number
          format: int32
          description: "[dBm]"
        srn:
          type: number
          format: int32
          description: "[dB]"
        ts:
          type: number
          format: int64
          description: "Timestamp"
        tmms:
          type: number
          format: int64
        time:
          type: string
          format: date-time
          description: "UTC time when message was received"
        gweui:
          type: string
          example: "B827EBFFFF2613D4"
          description: "LoraWAN GW identifier (16 HEX chars)"
        ant: 
          type: number
          format: int32
        lat:
          type: number
          format: double
          description: "latitude"
        lon:
          type: number
          format: double
          description: "longitude"
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/Michus001/CRA-IOT/1.0.0